#!/bin/bash
dir="/home/qaqulya/git-repos/opensuse_leap_kde";
cd "$dir";
dir="/home/qaqulya/.config";
cd "$dir";
#watchexec -i .git -r 'git add .; git commit -am "watchexec"; git push origin main' &
#nohup watchexec -i .git,.*Cache.* -r 'git add .; git commit -am "watchexec"; git push origin main'>/dev/null 2>&1 &
#cp -r {alacritty,aria2c,aria2p,autostart,custom,gtk-3.0,gtk-4.0,hud-menu,i3,lazygit,mc,micro,nvim,obsidian,qt5ct,pop-shell,qutebrowser,ranger,scripts,sway,waybar,wofi,youtube-dl,mimeapps.list} ~/git-repos/opensuse_leap_kde/.config
#nohup watchexec -i "Cache",".git" -f alacritty,aria2c,aria2p,autostart,custom,"gtk-3.0","gtk-4.0",hud-menu,i3,lazygit,mc,micro,nvim,obsidian,qt5ct,pop-shell,qutebrowser,ranger,scripts,sway,waybar,wofi,youtube-dl,mimeapps.list -r 'cp -r alacritty aria2c aria2p autostart custom gtk-3.0 gtk-4.0 hud-menu i3 lazygit mc micro nvim obsidian qt5ct pop-shell qutebrowser ranger scripts sway waybar wofi youtube-dl mimeapps.list ~/git-repos/opensuse_leap_kde/.config; cd ~/git-repos/opensuse_leap_kde; git add .; git commit -am "watchexec"; git push origin main' >/dev/null 2>&1 &

#nohup watchexec -f alacritty,aria2c,aria2p,autostart,custom,"gtk-3.0","gtk-4.0",hud-menu,i3,lazygit,mc,micro,nvim,obsidian,qt5ct,pop-shell,qutebrowser,ranger,scripts,sway,waybar,wofi,youtube-dl -r 'cp -r alacritty aria2c aria2p autostart custom gtk-3.0 gtk-4.0 hud-menu i3 lazygit mc micro nvim obsidian qt5ct pop-shell qutebrowser ranger scripts sway waybar wofi youtube-dl mimeapps.list ~/git-repos/opensuse_leap_kde/.config; cd ~/git-repos/opensuse_leap_kde; git add .; git commit -am "watchexec"; git push origin main' >/dev/null 2>&1 &


nohup watchexec -w autostart -w custom -w nvim -w obsidian -w qutebrowser -w scripts 'cp -r autostart custom nvim obsidian qutebrowser scripts ~/git-repos/opensuse_leap_kde/.config; cd ~/git-repos/opensuse_leap_kde; rsync -avh /home/qaqulya/.config ./.config --delete; git add .; git commit -am "watchexec"; git push origin main' >/dev/null 2>&1 &

#test
