#!/usr/bin/env python

import subprocess as sub
from pyrof.rofi import Rofi
from os import getenv, chdir

#url = "https://www.youtube.com/watch?v=77PaY0teSJ4".split("watch?v=")
url = getenv("QUTE_URL").split("watch?v=")
id_video = url[1]
user = getenv("USER")
d_dir = f"/home/{user}/Downloads"
chdir(d_dir)


def cekFormat(id_video):
    cek_format = sub.check_output(["youtube-dl", "-F", id_video], text=True).strip().split("\n")
    del cek_format[0:4]
    f_code = []
    for f in cek_format:
        x = f.replace("         ", "")
        x = x.replace("      ", "")
        x = x.replace(",", "")
        x = x.split()
        if x[3] == "only":
            del x[4:7]
        else:
            del x[3:6]
        x = " ".join(x)
        f_code.append(x)
    return f_code


def idFormat():
    f_code = cekFormat(id_video)
    pilih_format = Rofi(theme_str='inputbar {children: [prompt];} listview {columns: 1;} window {width: 1000px;}')
    pilih_format.prompt = "Format"
    pilih_format = pilih_format(f_code)
    id_format = pilih_format.selected.split()
    format_code = id_format[0]
    format_ex = id_format[1]
    return format_code, format_ex


def getTitle(id_video):
    title = sub.check_output(["youtube-dl", "-e", id_video], text=True).strip()
    return title


def download():
    title = getTitle(id_video)
    id_format = idFormat()
    notif("Start download")
    sub.run(["youtube-dl", "-f", id_format[0], "-o", "%(title)s.%(ext)s", "--external-downloader", "aria2c", id_video])
    cek_status = sub.check_output(["find", "-name", f"{title}.{id_format[1]}.part.aria2"], text=True).strip()
    if cek_status == "":
        notif("Finish download")
    else:
        notif("Download failed")
        opt = ("Yes", "No")
        retray_menu = Rofi(theme_str='inputbar {children: [prompt];} listview {lines: 1; columns: 2;} window {width : 350px;}')
        retray_menu.prompt = "Download failed cek your connection"
        retray_menu.mesg = "Retray Download ?"
        retray_menu = retray_menu(opt)
        c_opt = retray_menu.selected
        if c_opt == opt[0]:
            download()
        else:
            with open("id last download.txt", "x") as last_download:
                last_download.write(id_video)
            exit()


def notif(pesan):
    sub.run(["dunstify", "Youtube Downloader", pesan])


download()
