var isOpera=!!window.opera||-1<navigator.userAgent.indexOf(" OPR/"),isFirefox=-1<navigator.userAgent.toLowerCase().indexOf("firefox"),isChrome=!isOpera&&!isFirefox,storage=chrome.storage.local,storageSync=chrome.storage.sync,chromeVersion=/Chrome\/([0-9]+)/.exec(navigator.userAgent)[1],optExtraInfoSpec=["requestHeaders","blocking"];isChrome&&72<=chromeVersion&&optExtraInfoSpec.push("extraHeaders");
window.onload=function(){localStorage.removeItem("cache");localStorage.removeItem("cache_timestamp");localStorage.log="";localStorage.logActive||(localStorage.logActive="Off");localStorage.contextMenuActive||(localStorage.contextMenuActive="On");localStorage.settings?(rc.settings=JSON.parse(localStorage.settings),localStorage.settingsSynced||(localStorage.settingsSynced=!0,storage.set({RefererControlSettings:localStorage.settings},function(){chrome.runtime.lastError&&console.log("Error!: "+chrome.runtime.lastError)})),
rc.findDefaultAction()):storage.get("RefererControlSettings",function(b){if(chrome.runtime.lastError)console.log("Error!: "+chrome.runtime.lastError);else try{JSON.parse(b.RefererControlSettings).sites&&(localStorage.settings=b.RefererControlSettings,a())}catch(c){}localStorage.settings||(storageSync.get("RefererControlSettings",function(b){if(chrome.runtime.lastError)console.log("Error!: "+chrome.runtime.lastError);else try{JSON.parse(b.RefererControlSettings).sites&&(localStorage.settings=b.RefererControlSettings,
a())}catch(d){}localStorage.settings||(chrome.tabs.create({url:chrome.extension.getURL("chrome/content/options.html")}),localStorage.settings=JSON.stringify(rc.settings));storageSync.set({RefererControlSettings:localStorage.settings},function(){chrome.runtime.lastError?console.log("Error!: "+chrome.runtime.lastError):(localStorage.settingsSynced=!0,storage.set({RefererControlSettings:localStorage.settings},function(){}))});storage.set({RefererControlSettings:localStorage.settings},function(){})}),
localStorage.settings=JSON.stringify(rc.settings));storage.set({RefererControlSettings:localStorage.settings},function(){chrome.runtime.lastError&&console.log("Error!: "+chrome.runtime.lastError)})});var a=function(){var a=!1,c=rc.settings.sites,d=[],e;for(e in c){var f=c[e];"defaultAction"==f.id?d.push(f):void 0!=f.id&&void 0!=f.val&&void 0!=f.type&&void 0!=f.filter&&void 0!=f.isregexp&&void 0!=f.isfrom&&void 0!=f.isto&&void 0!=f.is3rd?d.push(f):a=!0}a&&(console.log("foundCorrupt site filter, repaired it."),
rc.settings.sites=d,localStorage.settings=JSON.stringify(rc.settings),rc.findDefaultAction())};a();window.addEventListener("storage",function(b){"settings"==b.key?void 0!=b.newValue&&(storage.set({RefererControlSettings:localStorage.settings},function(){}),storageSync.set({RefererControlSettings:localStorage.settings},function(){}),rc.settings=JSON.parse(localStorage.settings),rc.findDefaultAction(),a()):"contextMenuActive"==b.key&&rc.contextMenu()},!1);isChrome&&chrome.runtime.onMessageExternal.addListener(function(a,
c,d){"isActive"===a.type&&d({isActive:rc.settings.active})});chrome.webRequest.onBeforeSendHeaders.addListener(rc.onBeforeSendHeadersHandler,{urls:["<all_urls>"],types:"main_frame sub_frame stylesheet script image font object xmlhttprequest other".split(" ")},optExtraInfoSpec);"On"===localStorage.contextMenuActive&&rc.contextMenu();chrome.browserAction.onClicked.addListener(function(a){chrome.tabs.create({url:chrome.extension.getURL("chrome/content/options.html")})});chrome.runtime.onMessage.addListener(function(a,
c,d){switch(a.type){case "blockReferrer":var b={block:!1};if(rc.settings.jsBlock){var f=rc.testFiltersAgainstRequest(a.target,c.tab.url,rc.settings);f?"normal"!=f.type&&(b.block=!0):"normal"!=rc.settings.sites[rc.defaultAction].type&&(rc.settings.sites[rc.defaultAction].is3rd&&!rc.isThirdParty(a.target,c.tab.url)?b.block=!1:b.block=!0)}d(b);break;default:d({})}});setTimeout(function(){rc.update()},1E3)};
var rc={r:"",logMessage:"",logMsg:function(){"Off"!=localStorage.logActive&&(4E3<localStorage.log.length&&(localStorage.log=localStorage.log.substring(0,2E3)),rc.logMessage=rc.logMessage+"<br>"+localStorage.log,localStorage.log=rc.logMessage,rc.logMessage="")},settings:{sites:[{id:"defaultAction",val:"dummy",type:"normal",filter:""}],active:!0},findDefaultAction:function(){var a=rc.settings.sites,b;for(b in a)if("dummy"==a[b].val){"defaultAction"==a[b].id&&(rc.defaultAction=b);break}-1==rc.defaultAction&&
(a.push({id:"defaultAction",val:"dummy",type:"normal",filter:""}),rc.defaultAction=a.length-1,rc.save(),storage.set({RefererControlSettings:localStorage.settings},function(){}))},randomString:function(){for(var a="",b=Math.floor(10*Math.random())+2,c=0;c<b;c++)a+="abcdefghijklmnopqrstuvw".charAt(Math.floor(23*Math.random()));return a},randomTld:function(){var a=["com","net","info","org"];return""+a[Math.floor(Math.random()*(a.length-1))]},excapeRegexp:RegExp("([{}()^$&.*?/+|[\\\\]|]|-)","g"),escapeRegexpChars:function(a){return a.replace(rc.excapeRegexp,
"\\$1")},parseWildCard:function(a){a=a.replace(/^htt(p|ps):\\\/\\\//,"^htt$1://");return a.replace("\\*",".*?")},specificRegExp:/\[(URL|TARGET_HOST|REFERER_HOST|RANDOM)\]/,parseReferer:function(a,b,c){if(c.match(rc.specificRegExp))switch(RegExp.$1){case "URL":return c.replace("[URL]",b);case "TARGET_HOST":var d=document.createElement("a");d.href=b;return c.replace("[TARGET_HOST]",d.protocol+"//"+d.hostname);case "REFERER_HOST":if(""==a)return"";d=document.createElement("a");d.href=a;return c.replace("[REFERER_HOST]",
d.protocol+"//"+d.hostname);case "RANDOM":return"http://www."+rc.randomString()+"."+rc.randomTld()}return c},applyFilter:function(a,b,c,d){"block"==a.type?(rc.logMessage+=" - <b>blocked referer.</b><br>",0<=rc.refererIndex&&d.splice(rc.refererIndex,1)):"specific"==a.type&&(a=rc.parseReferer(c,b,a.filter),0>rc.refererIndex?d.push({name:"Referer",value:a}):d[rc.refererIndex].value=a,rc.logMessage+="<br>sent referer:&emsp;<span style='color:darkgreen'>"+a+"</span><br>");return d},isThirdParty:function(a,
b){if(""==b)return!1;try{var c=document.createElement("a");c.href=a;var d=c.hostname;c.href=b;return d!=c.hostname}catch(e){return!1}},refererIndex:-1,defaultAction:-1,testFilterAgainstRequest:function(a,b,c){if(c.is3rd&&!rc.isThirdParty(a,b))return!1;var d="";try{var e=c.isregexp?c.val:rc.parseWildCard(rc.escapeRegexpChars(c.val));d=new RegExp(e)}catch(f){return console.log("Referer Control filter error: invalid filter: "+c.val+" error: "+f.message),!1}return c.isto&&""!=a&&d.test(a)||c.isfrom&&
""!=b&&d.test(b)?!0:!1},testFiltersAgainstRequest:function(a,b,c){var d;for(d in c.sites){var e=c.sites[d];if(""!=e.val&&"dummy"!=e.val&&rc.testFilterAgainstRequest(a,b,e))return e}return!1},extractHeaderFromRequest:function(a,b){for(var c=rc.refererIndex=-1,d=0,e=a.length;d<e;++d)if(a[d].name.toLowerCase()===b.toLowerCase()){b=a[d].value;c=d;break}return[c,b]},onBeforeSendHeadersHandler:function(a){try{var b={},c=rc.settings,d=a.requestHeaders;if(!c.active)return{requestHeaders:a.requestHeaders};
var e=a.url,f=rc.extractHeaderFromRequest(d,"Referer"),g="Referer"==f[1]?"":f[1];rc.refererIndex=f[0];var h=rc.testFiltersAgainstRequest(e,g,c);if(h){if("normal"==h.type)return b;rc.logMessage='<span style="color:tomato">'+(new Date).format("D, M j G:i:s")+':</span> <br> requested:&emsp;<span style="color:#777">'+e+'</span><br>with referer:&emsp;<span style="color:#016157">'+g+'</span><br>matched filter:&emsp;<span style="color:#444">'+h.val+"</span>";b.requestHeaders=rc.applyFilter(h,e,g,d);rc.logMsg();
return b}if(-1==rc.defaultAction)return{};if("normal"!=c.sites[rc.defaultAction].type){if(c.sites[rc.defaultAction].is3rd&&!rc.isThirdParty(e,g))return{};rc.logMessage='<span style="color:tomato">'+(new Date).format("D, M j G:i:s")+':</span> <br> requested:&emsp;<span style="color:#777">'+a.url+'</span><br>matched filter:&emsp;<span style="color:#444">&lt; default action &gt;</span>';b.requestHeaders=rc.applyFilter(c.sites[rc.defaultAction],e,g,d);rc.logMsg();return b}return{requestHeaders:a.requestHeaders}}catch(k){return{}}},
index:0,r2ListenerIsActive:!0,rActive:!1,rActiveR8:!1,contextMenu:function(){if("Off"===localStorage.contextMenuActive)chrome.contextMenus.removeAll();else{var a=function(a,b,c){b="#"+c;b=0===c?"":a.hasOwnProperty("frameUrl")?b+a.frameUrl:b+a.pageUrl;chrome.tabs.create({url:chrome.extension.getURL("chrome/content/options.html"+b)})},b=chrome.contextMenus.create({title:"Create referer filter for this site",contexts:["page","frame"]});chrome.contextMenus.create({title:"Normal (Whitelist)",parentId:b,
onclick:function(b,c){a(b,c,1)}});var c=chrome.contextMenus.create({title:"Use custom referer",parentId:b});chrome.contextMenus.create({title:"Block referer",parentId:b,onclick:function(b,c){a(b,c,2)}});chrome.contextMenus.create({type:"separator",parentId:b});chrome.contextMenus.create({title:"Open options",parentId:b,onclick:function(b,c){a(b,c,0)}});var d=function(){return(rc.settings.active?"Deactivate":"Activate")+" Referer Control"},e=function(a,c){rc.settings.active=!rc.settings.active;rc.save();
chrome.contextMenus.update(f,{title:d(),parentId:b,onclick:e})},f=chrome.contextMenus.create({title:d(),parentId:b,onclick:e});chrome.contextMenus.create({title:" < disable context menu >",parentId:b,onclick:function(){chrome.contextMenus.removeAll();localStorage.contextMenuActive="Off"}});chrome.contextMenus.create({title:"Url",parentId:c,onclick:function(b,c){a(b,c,5)}});chrome.contextMenus.create({title:"Target host",parentId:c,onclick:function(b,c){a(b,c,6)}});chrome.contextMenus.create({title:"Referer host",
parentId:c,onclick:function(b,c){a(b,c,7)}});chrome.contextMenus.create({title:"Random",parentId:c,onclick:function(b,c){a(b,c,8)}})}},save:function(){localStorage.settings=JSON.stringify(rc.settings)},update:function(){try{localStorage.install?localStorage.installSynced||(storage.set({RefererControlInstall:localStorage.install},function(){}),localStorage.installSynced=!0):storage.get("RefererControlInstall",function(a){if(chrome.runtime.lastError)console.log("Error!: "+chrome.runtime.lastError);
else try{13==a.RefererControlInstall.length&&(localStorage.install=a.RefererControlInstall,console.log("loaded install from sync"))}catch(b){}localStorage.install||(localStorage.install=Date.now(),storage.set({RefererControlInstall:localStorage.install},function(){}))})}catch(a){}},httpGet:function(a,b){var c=new XMLHttpRequest;b&&(c.onreadystatechange=function(){4==c.readyState&&b.call(this,c.responseText)});c.open("GET",a,!0);c.send()}};
Date.prototype.format=function(a){for(var b="",c=Date.replaceChars,d=0;d<a.length;d++){var e=a.charAt(d);0<=d-1&&"\\"==a.charAt(d-1)?b+=e:c[e]?b+=c[e].call(this):"\\"!=e&&(b+=e)}return b};
Date.replaceChars={shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),longMonths:"January February March April May June July August September October November December".split(" "),shortDays:"Sun Mon Tue Wed Thu Fri Sat".split(" "),longDays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),d:function(){return(10>this.getDate()?"0":"")+this.getDate()},D:function(){return Date.replaceChars.shortDays[this.getDay()]},j:function(){return this.getDate()},l:function(){return Date.replaceChars.longDays[this.getDay()]},
N:function(){return this.getDay()+1},S:function(){return 1==this.getDate()%10&&11!=this.getDate()?"st":2==this.getDate()%10&&12!=this.getDate()?"nd":3==this.getDate()%10&&13!=this.getDate()?"rd":"th"},w:function(){return this.getDay()},z:function(){var a=new Date(this.getFullYear(),0,1);return Math.ceil((this-a)/864E5)},W:function(){var a=new Date(this.getFullYear(),0,1);return Math.ceil(((this-a)/864E5+a.getDay()+1)/7)},F:function(){return Date.replaceChars.longMonths[this.getMonth()]},m:function(){return(9>
this.getMonth()?"0":"")+(this.getMonth()+1)},M:function(){return Date.replaceChars.shortMonths[this.getMonth()]},n:function(){return this.getMonth()+1},t:function(){var a=new Date;return(new Date(a.getFullYear(),a.getMonth(),0)).getDate()},L:function(){var a=this.getFullYear();return 0==a%400||0!=a%100&&0==a%4},o:function(){var a=new Date(this.valueOf());a.setDate(a.getDate()-(this.getDay()+6)%7+3);return a.getFullYear()},Y:function(){return this.getFullYear()},y:function(){return(""+this.getFullYear()).substr(2)},
a:function(){return 12>this.getHours()?"am":"pm"},A:function(){return 12>this.getHours()?"AM":"PM"},B:function(){return Math.floor(1E3*((this.getUTCHours()+1)%24+this.getUTCMinutes()/60+this.getUTCSeconds()/3600)/24)},g:function(){return this.getHours()%12||12},G:function(){return this.getHours()},h:function(){return(10>(this.getHours()%12||12)?"0":"")+(this.getHours()%12||12)},H:function(){return(10>this.getHours()?"0":"")+this.getHours()},i:function(){return(10>this.getMinutes()?"0":"")+this.getMinutes()},
s:function(){return(10>this.getSeconds()?"0":"")+this.getSeconds()},u:function(){var a=this.getMilliseconds();return(10>a?"00":100>a?"0":"")+a},e:function(){return"Not Yet Supported"},I:function(){return"Not Yet Supported"},O:function(){return(0>-this.getTimezoneOffset()?"-":"+")+(10>Math.abs(this.getTimezoneOffset()/60)?"0":"")+Math.abs(this.getTimezoneOffset()/60)+"00"},P:function(){return(0>-this.getTimezoneOffset()?"-":"+")+(10>Math.abs(this.getTimezoneOffset()/60)?"0":"")+Math.abs(this.getTimezoneOffset()/
60)+":00"},T:function(){var a=this.getMonth();this.setMonth(0);var b=this.toTimeString().replace(/^.+ \(?([^\)]+)\)?$/,"$1");this.setMonth(a);return b},Z:function(){return 60*-this.getTimezoneOffset()},c:function(){return this.format("Y-m-d\\TH:i:sP")},r:function(){return this.toString()},U:function(){return this.getTime()/1E3}};