var bgPage=chrome.extension.getBackgroundPage(),pageNotes={},tagIndex={};function extractTags(a){return a?$.parseHTML(a).map(function(b){return $("<div>").html(b).text()}).join(" ").replace(/(\n|\t)+/g," ").split(" ").filter(function(b){return b.match(/^#/)}):[]}function markupTagsInNotes(a){for(var b=extractTags(a),c=0;c<b.length;c++){var d=b[c],e="tag-link";d===window.location.hash&&(e+=" selected-tag");a=a.replace(d,'<a class="'+e+'" href="">'+d+"</a>")}return a}var reload=function(){location.reload()};
function initPage(){pageNotes=(new PageNotes).getAll();buildTagCloud();var a=[];$.each(pageNotes,function(g,l){""===window.location.hash?a.push(g):-1!=tagIndex[window.location.hash].indexOf(g)&&a.push(g)});a.sort();for(var b=$("#all-notes").html(""),c=0;c<a.length;c++){var d=$("<tr/>").appendTo(b),e=$("<a/>").attr("href",a[c]).html(a[c]).appendTo($("<td/>").addClass("urlTD").appendTo(d));"chrome-extension:"==e.prop("protocol")&&e.attr("href","http://"+a[c]);var f=pageNotes[a[c]];if(3<=f.length&&f[2]){var h=
"***************";e="Decrypt";var k="decryptB"}else h=markupTagsInNotes(f[0]),e="Edit",k="editB";f=formatDate(f[1]);$("<div/>").addClass("date-div").html(f).appendTo($("<td/>").appendTo(d));$("<div/>").addClass("notes-div").html(h).appendTo($("<td/>").addClass("notesTD").appendTo(d));d=$("<td/>").addClass("buttons").appendTo(d);$("<button/>").addClass(k).html(e).appendTo(d);$("<button/>").addClass("deleteB").html("Delete").appendTo(d).click({key:a[c]},function(g){bgPage.deleteButtonHandler(this,g.data.key,
reload,"Are you sure you want to delete these notes? ")})}b.on("click","button.editB",Edit);b.on("click","button.decryptB",Edit);b.on("click","button.saveB",Save);b.on("click","button.cancelB",Cancel);$("#notesTable").trigger("update",[!0])}function formatDate(a){a=new Date(a);return a.toDateString().replace(/^[^ ]+ /,"")+" "+a.toTimeString().replace(/ GMT.*$/,"")}function warning(a,b){var c=a.find(".warning");0==c.length&&(c=$("<div/>").addClass("warning").appendTo(a));c.html(b)}
function handleDecrypt(a,b,c){var d=a.children("td:nth-child(4)"),e=a.find(".passphrase-label");if(0==e.length)e=$("<label/>").css("margin-bottom","5px").addClass("passphrase-label").html("Passphrase: ").prependTo(d),$("<input/>").prop("type","password").addClass("passphrase-input").appendTo(e);else{var f=a.find(".passphrase-input")[0].value;""===f?warning(d,"Passphrase cannot be empty."):(b=bgPage.CryptoJS.AES.decrypt(pageNotes[b][0],f).toString(bgPage.CryptoJS.enc.Utf8),""===b?warning(d,"Wrong passphrase."):
(a.find(".notes-div").html(b),c.html("Hide"),e.remove()))}}
function Edit(a){a=$(this).parent().parent();warning(a,"");var b=a.children("td:nth-child(1)").children("a:nth-child(1)").html();if("Decrypt"===$(this).html())handleDecrypt(a,b,$(this));else{var c=a.find(".notes-div");"Hide"===$(this).html()?($(this).html("Decrypt"),c.html("**********")):(c.html(pageNotes[b][0]),c.addClass("editable"),c.focus(),moveCursorToTheEnd(c.get(0)),$(this).html("Save"),$(this).removeClass().addClass("saveB"),b=document.createElement("button"),$(b).html("Cancel"),$(b).removeClass().addClass("cancelB"),
a.find(".deleteB").replaceWith($(b)))}}function Cancel(){var a=$(this).parent().parent(),b=a.children("td:nth-child(1)").children("a:nth-child(1)").html(),c=a.find(".notes-div");a=a.find(".saveB");c.html(pageNotes[b][0]);c.removeClass("editable");a.html("Edit");a.removeClass().addClass("editB");b=bgPage.deleteButton("Delete",b,reload,"Are you sure you want to delete these notes? ");$(this).replaceWith($(b))}
function Save(a){var b=$(this).parent().parent();a=b.children("td:nth-child(1)").children("a:nth-child(1)").html();b=b.find(".notes-div");b.removeClass("editable");b.css("color","#111");(new PageNotes).set(a,b.html());localStorage.lastModTime=(new Date).getTime();$(this).html("Edit");$(this).removeClass().addClass("editB");location.reload()}
function buildTagIndex(){for(var a in pageNotes){var b=extractTags(pageNotes[a][0]);if(b)for(var c=0;c<b.length;c++)b[c]in tagIndex||(tagIndex[b[c]]=[]),-1===tagIndex[b[c]].indexOf(a)&&tagIndex[b[c]].push(a)}}
function buildTagCloud(){buildTagIndex();var a=[],b;for(b in tagIndex)a.push({key:b,value:tagIndex[b].length});a.sort(function(c,d){return c.value>d.value?-1:c.value<d.value||c.key>d.key?1:c.key<d.key?-1:0});$("#tag-cloud").html("");$("#tag-cloud").append('<li><a class="tag-link" href="">All</a></li>');for(b=0;b<a.length;b++)window.location.hash===a[b].key?$("#tag-cloud").append('<li><a class="tag-link selected-tag" href="">'+a[b].key+"("+a[b].value+")</a></li>"):$("#tag-cloud").append('<li><a class="tag-link" href="">'+
a[b].key+"("+a[b].value+")</a></li>")}$(document).on("click",".tag-link",function(){var a=$(this).html();a.match(/(.*)\([0-9]+\)/)&&(a=a.match(/(.*)\([0-9]+\)/)[1]);-1==$(this).attr("class").indexOf("selected-tag")?window.location.hash=a:(window.location.hash="",window.location.href=window.location.href.replace(/#$/,""));initPage();return!1});
function moveCursorToTheEnd(a){var b=document.createRange();b.selectNodeContents(a);b.collapse(!1);a=window.getSelection();a.removeAllRanges();a.addRange(b)}function exportToCsv(){var a=(new PageNotes).csvFormat();$(".exportAnchor").attr("href","data:text/csv,"+encodeURIComponent(a))}
document.addEventListener("DOMContentLoaded",function(){$(".exportButton").click(exportToCsv);initPage();$("#notesTable").tablesorter({theme:"default",headerTemplate:"{content}{icon}",headers:{3:{sorter:!1}},sortList:[[0,0]]})});
