var SYNC_INTERVAL=3E5,DRIVE_SCOPE="https://www.googleapis.com/auth/drive.file",REMOTE_FILE_NAME="pagenotes.data",RED_COLOR={color:[255,0,0,255]},GREEN_COLOR={color:[42,115,109,255]},oauth=null,pageNotes=new PageNotes,options=new Options;function setUpOauth(){oauth=new OAuth2}
chrome.storage.onChanged.addListener(function(a,b){void 0!==a.oauth2&&JSON.parse(a.oauth2.newValue).client_id==defaultOauthConfig.client_id&&(console.log("Changing the local oauth setup to use the new client id"),localStorage.oauth2=newValue,oauth=new OAuth2,localStorage.gFile&&getRemoteFile())});var debug={msg:"",log:function(a){this.msg+=a+"\n"}},lastSyncStatus;chrome.tabs.onSelectionChanged.addListener(function(a){chrome.tabs.get(a,updateBadgeForTab)});
chrome.tabs.onUpdated.addListener(function(a,b,c){updateBadgeForTab(c)});function getHostFromUrl(a){var b=document.createElement("a");b.href=a;return b.hostname}function setIcon(a,b,c){chrome.browserAction.setIcon({path:{19:"icons/icon"+b+"_19.png",38:"icons/icon"+b+"_38.png"},tabId:a.id});chrome.browserAction.setBadgeText({text:c,tabId:a.id})}
function updateBadgeForTab(a){var b=a.url,c=getHostFromUrl(b);pageNotes.get(b)||pageNotes.get(c)?bgPage.options.get("old_icons")?setIcon(a,"_old","pn"):setIcon(a,"_filled",""):bgPage.options.get("old_icons")?setIcon(a,"_old","0"):setIcon(a,"","")}function saveGFile(a){localStorage.gFile=a}function getRemoteFile(){return new GoogleFile(localStorage.gFile,saveGFile)}
function setVisualCues(){2<=getSyncFailCount()?(chrome.browserAction.setBadgeBackgroundColor(RED_COLOR),chrome.browserAction.setTitle({title:"Page Notes - Sync is not happening."})):(chrome.browserAction.setBadgeBackgroundColor(GREEN_COLOR),chrome.browserAction.setTitle({title:"Page Notes"}))}
function initOAuth(){localStorage.oauth2?(setUpOauth(),chrome.storage.sync.get("oauth2",function(a){void 0===a.oauth2&&chrome.storage.sync.set({oauth2:localStorage.oauth2})})):chrome.storage.sync.get("oauth2",function(a){void 0!==a.oauth2&&(localStorage.oauth2=a.oauth2,setUpOauth())})}
function sync(){debug.msg="";debug.log("sync: Starting sync at: "+new Date);oauth||initOAuth();if(oauth&&oauth.hasAccessToken())if(localStorage.gFile){var a=getRemoteFile();try{"true"===localStorage.firstSync?(debug.log("sync: First sync, merging local and remote data."),mergeLocalAndRemoteData(a),localStorage.firstSync="false"):a.refreshLocalMetadata(syncData)}catch(b){lastSyncStatus="bad";incSyncFailCount();setVisualCues();debug.log(b);return}lastSyncStatus="good";resetSyncFailCount();localStorage.lastSyncTime=
new Date;setVisualCues()}else setVisualCues(),debug.log("sync: Sync gdoc is not setup.");else setVisualCues(),debug.log("sync: No Oauth token found.")}
function syncData(a){var b=0;localStorage.lastModTime&&(b=parseInt(localStorage.lastModTime,10));var c=parseInt(a.getLastUpdateTime(),10);debug.log("sync: Local last mod time: "+b);debug.log("sync: Remote last mod time: "+c);c===b?debug.log("sync: Local and remote data are equally recent."):c>b?(debug.log("sync: Remote data is more recent."),a.getData(pageNotes.setSource.bind(pageNotes)),localStorage.lastModTime=a.getLastUpdateTime(),convertPageNotes()):(debug.log("sync: Local data is more recent."),
a.setData(pageNotes.getSource()),localStorage.lastModTime=a.getLastUpdateTime())}
function mergeLocalAndRemoteData(a){var b=pageNotes.getSource();if(b){var c=JSON.parse(b),g=0;localStorage.lastModTime&&(g=parseInt(localStorage.lastModTime,10));var h=parseInt(a.getLastUpdateTime(),10)>g;a.getData(function(e){var d,k={};if(""===e.trim())f=b;else{e=JSON.parse(e);for(d in c)c.hasOwnProperty(d)&&(k[d]=c[d],e.hasOwnProperty(d)&&h&&(k[d]=e[d],delete e[d]));for(d in e)e.hasOwnProperty(d)&&(k[d]=e[d]);f=JSON.stringify(k)}});var f=convertPageNotesString(f);pageNotes.setSource(f);a.setData(f);
localStorage.lastModTime=a.getLastUpdateTime()}else a.getData(pageNotes.setSource.bind(pageNotes)),localStorage.lastModTime=a.getLastUpdateTime(),convertPageNotes()}function incSyncFailCount(){localStorage.syncFailCount=localStorage.syncFailCount?parseInt(localStorage.syncFailCount,10)+1:"1"}function resetSyncFailCount(){localStorage.syncFailCount="0"}function getSyncFailCount(){localStorage.syncFailCount||(localStorage.syncFailCount="0");return parseInt(localStorage.syncFailCount,10)}
function init(){versionTracking();convertPageNotes();handleFirstRun();handleIconsUpdate();sync()}function convertPageNotes(){if(pageNotes.getSource()){var a=convertPageNotesString(pageNotes.getSource());a!==pageNotes.getSource()&&(pageNotes.setSource(a),localStorage.lastModTime=(new Date).getTime(),sync())}}function convertPageNotesString(a){a=JSON.parse(a);var b=new Date,c;for(c in a)"string"==typeof a[c]&&(a[c]=[a[c],b]);return JSON.stringify(a)}
function versionTracking(){var a=chrome.runtime.getManifest();localStorage.currentVersion&&localStorage.currentVersion===a.version||(localStorage.lastVersion=localStorage.currentVersion,localStorage.currentVersion=a.version)}function handleIconsUpdate(){var a="";localStorage.lastVersion&&(a=localStorage.lastVersion.replace(/(\d+\.\d+)\.\d+/,"$1"));"2.3"!==a||localStorage.warnedAboutIcons||chrome.tabs.create({url:chrome.extension.getURL("options.html")})}
function handleFirstRun(){localStorage.runOnce||(localStorage.runOnce=!0,localStorage.gFile||chrome.tabs.create({url:chrome.extension.getURL("options.html")}))}
function deleteButtonHandler(a,b,c,g){if("No"===a.innerHTML)c();else if("Yes"!==a.innerHTML&&"No"!==a.innerHTML){for(a=a.parentNode;a.firstChild;)a.removeChild(a.firstChild);a.innerHTML=g;g=["Yes","No"];for(var h=0;h<g.length;h++){var f=document.createElement("button");f.innerHTML=g[h];f.addEventListener("click",function(){deleteButtonHandler(this,b,c,"")});a.appendChild(f)}}else pageNotes.remove(b),localStorage.lastModTime=(new Date).getTime(),c()}
document.addEventListener("DOMContentLoaded",function(){window.setInterval(sync,SYNC_INTERVAL);init()});
