var defaultOauthConfig={client_id:"441023963490-4cdtujanvj3f8povmndgm5pddcgrq1l4.apps.googleusercontent.com",client_secret:"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",api_scope:"https://www.googleapis.com/auth/drive.file",redirect_url:"urn:ietf:wg:oauth:2.0:oob"},OAuth2=function(){var a=this.get();a.clientId||(a.clientId=defaultOauthConfig.client_id,a.clientSecret=defaultOauthConfig.client_secret,a.apiScope=defaultOauthConfig.api_scope,a.redirectURL=defaultOauthConfig.redirect_url,a.accessTokenURL="https://accounts.google.com/o/oauth2/token",
this.setSource(a))};OAuth2.prototype.authorizationCodeURL=function(a){return"https://accounts.google.com/o/oauth2/auth?client_id={{CLIENT_ID}}&redirect_uri={{REDIRECT_URI}}&scope={{API_SCOPE}}&access_type=offline&response_type=code".replace("{{CLIENT_ID}}",a.clientId).replace("{{REDIRECT_URI}}",a.redirectURL).replace("{{API_SCOPE}}",a.apiScope)};OAuth2.prototype.parseAuthorizationCode=function(a){var b=a.match(/[&\?]error=([^&]+)/);if(b)throw"Error getting authorization code: "+b[1];return a.match(/Success code=([\w\/\-]+)/)[1]};
OAuth2.prototype.accessTokenParams=function(a,b){return{code:a,client_id:b.clientId,client_secret:b.clientSecret,redirect_uri:b.redirectURL,grant_type:"authorization_code"}};OAuth2.prototype.parseAccessToken=function(a){a=JSON.parse(a);return{accessToken:a.access_token,refreshToken:a.refresh_token,expiresIn:a.expires_in}};
OAuth2.prototype.openAuthorizationCodePopup=function(a){var b=this;chrome.tabs.create({url:this.authorizationCodeURL(this.getConfig())},function(c){chrome.tabs.onUpdated.addListener(function(e,d,f){if(e===c.id&&"complete"===d.status&&0<f.title.search("code")){var g=f.title;chrome.tabs.remove(c.id,function(){b.finishAuth(g,a)})}})})};
OAuth2.prototype.getAccessAndRefreshTokens=function(a,b){var c=this,e=new XMLHttpRequest;e.addEventListener("readystatechange",function(g){4===e.readyState&&200===e.status&&b(c.parseAccessToken(e.responseText))});a=c.accessTokenParams(a,c.getConfig());var d=null,f=new FormData;for(d in a)f.append(d,a[d]);e.open("POST",c.get("accessTokenURL"),!0);e.send(f)};
OAuth2.prototype.refreshAccessToken=function(a,b){var c=new XMLHttpRequest;c.onreadystatechange=function(f){4===c.readyState&&200===c.status&&(f=JSON.parse(c.responseText),b(f.access_token,f.expires_in))};var e=this.get(),d=new FormData;d.append("client_id",e.clientId);d.append("client_secret",e.clientSecret);d.append("refresh_token",a);d.append("grant_type","refresh_token");c.open("POST",this.get("accessTokenURL"),!0);c.send(d)};
OAuth2.prototype.finishAuth=function(a,b){var c=null,e=this;try{c=e.parseAuthorizationCode(a)}catch(d){console.error(d)}e.getAccessAndRefreshTokens(c,function(d){var f=e.get();f.accessTokenDate=(new Date).valueOf();for(var g in d)d.hasOwnProperty(g)&&d[g]&&(f[g]=d[g]);e.setSource(f);b()})};OAuth2.prototype.isAccessTokenExpired=function(){var a=this.get();return(new Date).valueOf()-a.accessTokenDate>1E3*(a.expiresIn-30)};
OAuth2.prototype.get=function(a){var b=this.getSource();b=b?JSON.parse(b):{};return a?b[a]:b};OAuth2.prototype.set=function(a,b){var c=this.get();c[a]=b;this.setSource(c)};OAuth2.prototype.clear=function(a){if(a){var b=this.get();delete b[a];this.setSource(b)}else delete localStorage.oauth2};OAuth2.prototype.getSource=function(){return localStorage.oauth2};OAuth2.prototype.setSource=function(a){a&&("string"!==typeof a&&(a=JSON.stringify(a)),localStorage.oauth2=a)};
OAuth2.prototype.getConfig=function(){var a=this.get();return{clientId:a.clientId,clientSecret:a.clientSecret,apiScope:a.apiScope,redirectURL:a.redirectURL}};OAuth2.prototype.authorize=function(a){var b=this,c=b.get();c.accessToken?b.isAccessTokenExpired()?c.refreshToken?b.refreshAccessToken(c.refreshToken,function(e,d){var f=b.get();f.accessTokenDate=(new Date).valueOf();f.accessToken=e;f.expiresIn=d;b.setSource(f);a&&a.call(b)}):b.openAuthorizationCodePopup(a):a&&a.call(b):b.openAuthorizationCodePopup(a)};
OAuth2.prototype.getAccessToken=function(){return this.get("accessToken")};OAuth2.prototype.hasAccessToken=function(){return!!this.get("accessToken")};OAuth2.prototype.clearAccessToken=function(){this.clear("accessToken")};OAuth2.prototype.getAuthorizationHeader=function(a){this.authorize(function(){a("Bearer "+this.get("accessToken"))})};
