var bgPage=chrome.extension.getBackgroundPage();function e(a){return document.getElementById(a)}function notify(a,b){"info"===b?e("error").style.backgroundColor="moccasin":"warn"===b&&(e("error").style.backgroundColor="gold");e("error").innerHTML=a}
function setupSync(){bgPage.debug.msg="";try{if(!bgPage.oauth||!bgPage.oauth.hasAccessToken()){if(!confirm("You'll be redirected to Google website to set up authentication."))return;localStorage.nextAction="setup_sync";bgPage.oauth||bgPage.setUpOauth();bgPage.oauth.authorize(function(){chrome.storage.sync.set({oauth2:localStorage.oauth2},function(){console.log("Added oauth2 to chrome.storage")});location.reload()});return}if(!localStorage.gFile){var a=new bgPage.GoogleFile(null,bgPage.saveGFile);
a.searchFileByName(bgPage.REMOTE_FILE_NAME,function(){localStorage.gFile||(a.createNewFile(bgPage.REMOTE_FILE_NAME),localStorage.lastModTime=(new Date).getTime());localStorage.nextAction="setup_sync";location.reload()})}}catch(b){notify('There was an error in setting up sync. Click on "Debug info" for moreinformation.',"warn");bgPage.debug.log(b);return}bgPage.lastSyncStatus="";localStorage.firstSync="true";location.reload()}
function handleSyncButton(){"cancel_sync"===e("setup_sync").name?confirm("Are you sure you want to clear the sync setup?")&&(localStorage.removeItem("gFile"),bgPage.oauth.clear(),chrome.storage.sync.remove("oauth2"),bgPage.oauth=null,bgPage.lastSyncStatus="",location.reload()):setupSync()}
function updateFeatureButtons(){for(var a=[],b=document.getElementsByClassName("feature_option"),c=0;c<b.length;c++)a.push(b[c].id);a.forEach(function(d){var f=bgPage.options.get(d);"undefined"!=typeof f&&(e(d).checked=f);e(d).addEventListener("change",function(){bgPage.options.set(d,e(d).checked)})})}
function syncStatus(){var a=e("setup_sync");e("auth_button");var b=e("sync_status"),c=e("sync_now");if(localStorage.gFile){var d=bgPage.getRemoteFile();d&&d.get("alternateLink")&&(b.innerHTML='Syncing to <a href="'+d.get("alternateLink")+'">this file</a>. ');a.innerHTML="Stop Syncing";a.name="cancel_sync";c.disabled=!1}else b.innerHTML="Not syncing now. ",a.innerHTML="Setup Sync",a.name="setup_sync",c.disabled=!0,bgPage.lastSyncStatus="";"good"===bgPage.lastSyncStatus?(a=Math.floor((new Date-new Date(localStorage.lastSyncTime))/
6E4),b.innerHTML+="Synced "+(0===a?"less than a minute ago.":a+" min ago.")):bgPage.lastSyncStatus&&notify('There was an error during sync. Click on "Show debug info" for moreinformation.',"warn")}function setupShowHideElements(){for(var a=document.getElementsByClassName("show_hide"),b=0;b<a.length;b++)a[b].addEventListener("click",function(){var c=this.id.replace("show_","");"none"===e(c).style.display?e(c).style.display="block":e(c).style.display="none"})}
function CSVToArray(a,b){b=b||",";for(var c=new RegExp("(\\"+b+'|\\r?\\n|\\r|^)(?:"([^"]*(?:""[^"]*)*)"|([^"\\'+b+"\\r\\n]*))","gi"),d=[[]],f;f=c.exec(a);){var g=f[1];g.length&&g!==b&&d.push([]);f=f[2]?f[2].replace(RegExp('""',"g"),'"'):f[3];d[d.length-1].push(f)}return d}
function readSingleFile(a){var b=a.target.files[0];b?(a=new FileReader,a.onload=function(c){c=CSVToArray(c.target.result);if(confirm("Are you sure you want to import "+(c.length-1).toString()+" notes from this file: "+b.name+"? These notes will replace your existing notes for the same URLs.")&&confirm("Once more. Proceed with replacing the data?")){for(var d=1;d<c.length;d++){var f=!1,g=c[d];4<=g.length&&"true"==g[3]&&(f=!0);bgPage.pageNotes.set(g[0],g[2],Date.parse(g[1]),f)}localStorage.lastModTime=
new Date;notify('Imported notes data from "'+b.name+'".',"info")}},a.readAsText(b),e("importfile").value=""):alert("Failed to load file")}
function setupHandlers(){setupShowHideElements();e("setup_sync").addEventListener("click",handleSyncButton);e("sync_now").addEventListener("click",function(){bgPage.sync();location.reload()});e("clear_local").addEventListener("click",function(){confirm("Are you sure you want to delete all local data?")&&(localStorage.removeItem("pagenotes"),location.reload())});e("exportButton").addEventListener("click",function(){var a=bgPage.pageNotes.csvFormat();e("exportAnchor").setAttribute("href","data:text/csv,"+
encodeURIComponent(a))});e("importfile").addEventListener("change",readSingleFile);e("importfileButton").addEventListener("click",function(){e("importfile").click()})}
function checkAndNotify(){localStorage.currentVersion.replace(/(\d+\.\d+)\.\d+/,"$1");if(localStorage.lastVersion)var a=localStorage.lastVersion.replace(/(\d+\.\d+)\.\d+/,"$1");"2.3"!==a||localStorage.warnedAboutIcons||(notify("Important: Page notes icons have changed significantly. Please accustom yourself with the new icons. If you'd rather keep using old icons, you can do so by selecting 'Use old browser icons' on the 'Options' page.","info"),localStorage.warnedAboutIcons=!0)}
function init(){checkAndNotify();e("debug").innerHTML="Messages from last sync: \n"+bgPage.debug.msg;syncStatus();updateFeatureButtons();setupHandlers();bgPage.pageNotes.getSource()||(e("clear_local").disabled=!0);localStorage.hasOwnProperty("nextAction")&&"setup_sync"===localStorage.nextAction&&(localStorage.nextAction="",setupSync())}document.addEventListener("DOMContentLoaded",init);
